version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - development-network
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /opt/data/mysql':/var/lib/mysql

networks:
  development-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local